using System.ComponentModel;
using System.Runtime.CompilerServices;
using OpenSourceHub.Domain.Enums;

namespace OpenSourceHub.Localization;

public class LocalizationManager : INotifyPropertyChanged
{
    private static LocalizationManager? _instance;
    public static LocalizationManager Instance => _instance ??= new LocalizationManager();

    private AppLanguage _currentLanguage = AppLanguage.English;
    private readonly Dictionary<AppLanguage, Dictionary<string, string>> _strings = new();

    public event PropertyChangedEventHandler? PropertyChanged;

    private LocalizationManager()
    {
        LoadStrings();
    }

    public AppLanguage CurrentLanguage
    {
        get => _currentLanguage;
        set
        {
            if (_currentLanguage == value) return;
            _currentLanguage = value;
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(null));
        }
    }

    public string this[string key] => GetString(key);

    public string GetString(string key)
    {
        if (_strings.TryGetValue(_currentLanguage, out var dict) && dict.TryGetValue(key, out var val))
            return val;
        if (_strings.TryGetValue(AppLanguage.English, out var eng) && eng.TryGetValue(key, out var engVal))
            return engVal;
        return key;
    }

    private void LoadStrings()
    {
        _strings[AppLanguage.English] = GetEnglishStrings();
        _strings[AppLanguage.Turkish] = GetTurkishStrings();
        _strings[AppLanguage.Russian] = GetRussianStrings();
    }

    private static Dictionary<string, string> GetEnglishStrings() => new()
    {
        // Navigation
        ["Nav.Dashboard"] = "Dashboard",
        ["Nav.Repositories"] = "Repositories",
        ["Nav.Analyze"] = "Analyze",
        ["Nav.Trending"] = "Trending",
        ["Nav.Organizations"] = "Organizations",
        ["Nav.Contributors"] = "Contributors",
        ["Nav.Compare"] = "Compare",
        ["Nav.Security"] = "Security",
        ["Nav.AI"] = "AI Insights",
        ["Nav.Reports"] = "Reports",
        ["Nav.Favorites"] = "Favorites",
        ["Nav.Logs"] = "Logs",
        ["Nav.Settings"] = "Settings",

        // Auth
        ["Auth.SignIn"] = "Sign in with GitHub",
        ["Auth.SignOut"] = "Sign Out",
        ["Auth.EnterToken"] = "Enter GitHub Personal Access Token",
        ["Auth.TokenPlaceholder"] = "ghp_xxxxxxxxxxxxxxxxxxxx",
        ["Auth.SignInButton"] = "Authenticate",
        ["Auth.Cancel"] = "Cancel",
        ["Auth.Authenticating"] = "Authenticating...",
        ["Auth.Success"] = "Successfully authenticated!",
        ["Auth.Failed"] = "Authentication failed. Please check your token.",
        ["Auth.TokenHelp"] = "Generate a token at GitHub Settings → Developer settings → Personal access tokens",
        ["Auth.Required"] = "GitHub authentication is required.",
        ["Auth.SwitchAccount"] = "Switch Account",
        ["Auth.ManageTokens"] = "Manage Tokens",

        // Dashboard
        ["Dashboard.Title"] = "Dashboard",
        ["Dashboard.Welcome"] = "Welcome back,",
        ["Dashboard.TotalRepos"] = "Total Repositories",
        ["Dashboard.TotalStars"] = "Total Stars",
        ["Dashboard.TotalForks"] = "Total Forks",
        ["Dashboard.OpenIssues"] = "Open Issues",
        ["Dashboard.PullRequests"] = "Pull Requests",
        ["Dashboard.Followers"] = "Followers",
        ["Dashboard.Following"] = "Following",
        ["Dashboard.RecentActivity"] = "Recent Activity",
        ["Dashboard.TopRepositories"] = "Top Repositories",
        ["Dashboard.Loading"] = "Loading dashboard...",
        ["Dashboard.Refresh"] = "Refresh",
        ["Dashboard.ViewAll"] = "View All",
        ["Dashboard.Contributions"] = "Contributions",
        ["Dashboard.PublicRepos"] = "Public Repositories",

        // Repository
        ["Repo.Analyze"] = "Analyze Repository",
        ["Repo.SearchPlaceholder"] = "Enter owner/repository or URL...",
        ["Repo.Search"] = "Search",
        ["Repo.Analyzing"] = "Analyzing repository...",
        ["Repo.NotFound"] = "Repository not found.",
        ["Repo.HealthScore"] = "Health Score",
        ["Repo.MaintenanceScore"] = "Maintenance Score",
        ["Repo.SecurityScore"] = "Security Score",
        ["Repo.CommunityScore"] = "Community Score",
        ["Repo.PopularityScore"] = "Popularity Score",
        ["Repo.ActivityScore"] = "Activity Score",
        ["Repo.Stars"] = "Stars",
        ["Repo.Forks"] = "Forks",
        ["Repo.Watchers"] = "Watchers",
        ["Repo.Issues"] = "Issues",
        ["Repo.Language"] = "Language",
        ["Repo.License"] = "License",
        ["Repo.Created"] = "Created",
        ["Repo.Updated"] = "Updated",
        ["Repo.LastCommit"] = "Last Commit",
        ["Repo.Contributors"] = "Contributors",
        ["Repo.Releases"] = "Releases",
        ["Repo.Branches"] = "Branches",
        ["Repo.Recommendations"] = "Recommendations",
        ["Repo.Warnings"] = "Warnings",
        ["Repo.Documentation"] = "Documentation",
        ["Repo.OpenGitHub"] = "Open on GitHub",
        ["Repo.AddFavorite"] = "Add to Favorites",
        ["Repo.RemoveFavorite"] = "Remove from Favorites",
        ["Repo.GenerateReport"] = "Generate Report",
        ["Repo.AiAnalysis"] = "AI Analysis",
        ["Repo.Topics"] = "Topics",
        ["Repo.CloneUrl"] = "Clone URL",
        ["Repo.CopyUrl"] = "Copy URL",
        ["Repo.Compare"] = "Compare",

        // Scores
        ["Score.Excellent"] = "Excellent",
        ["Score.Good"] = "Good",
        ["Score.Fair"] = "Fair",
        ["Score.Poor"] = "Poor",
        ["Score.Critical"] = "Critical",

        // Trending
        ["Trending.Title"] = "Trending Repositories",
        ["Trending.Today"] = "Today",
        ["Trending.ThisWeek"] = "This Week",
        ["Trending.ThisMonth"] = "This Month",
        ["Trending.AllLanguages"] = "All Languages",
        ["Trending.FilterLanguage"] = "Filter by Language",
        ["Trending.Loading"] = "Loading trending repositories...",
        ["Trending.Developers"] = "Trending Developers",

        // Security
        ["Security.Title"] = "Security Center",
        ["Security.Analyze"] = "Security Analysis",
        ["Security.Alerts"] = "Security Alerts",
        ["Security.NoAlerts"] = "No security issues found.",
        ["Security.RiskLevel"] = "Risk Level",
        ["Security.Category"] = "Category",
        ["Security.Recommendation"] = "Recommendation",
        ["Security.Critical"] = "Critical",
        ["Security.High"] = "High",
        ["Security.Medium"] = "Medium",
        ["Security.Low"] = "Low",
        ["Security.None"] = "None",
        ["Security.Report"] = "Security Report",

        // AI
        ["AI.Title"] = "AI Insights",
        ["AI.Summary"] = "Repository Summary",
        ["AI.Adoption"] = "Adoption Recommendation",
        ["AI.Risk"] = "Risk Report",
        ["AI.Improvements"] = "Improvement Suggestions",
        ["AI.Ask"] = "Ask AI",
        ["AI.Placeholder"] = "Ask anything about this repository...",
        ["AI.Generating"] = "Generating AI analysis...",
        ["AI.Provider"] = "AI Provider",
        ["AI.NotConfigured"] = "AI is not configured. Please set up your API key in Settings.",
        ["AI.Copy"] = "Copy Response",
        ["AI.Regenerate"] = "Regenerate",

        // Organizations
        ["Org.Title"] = "Organizations",
        ["Org.Search"] = "Search Organization",
        ["Org.Members"] = "Members",
        ["Org.Teams"] = "Teams",
        ["Org.Repositories"] = "Repositories",
        ["Org.NotFound"] = "Organization not found.",
        ["Org.Loading"] = "Loading organization...",

        // Contributors
        ["Contrib.Title"] = "Contributors",
        ["Contrib.Search"] = "Search Contributors",
        ["Contrib.Commits"] = "Commits",
        ["Contrib.Activity"] = "Activity",
        ["Contrib.Timeline"] = "Contribution Timeline",
        ["Contrib.TopContributors"] = "Top Contributors",
        ["Contrib.Loading"] = "Loading contributors...",

        // Compare
        ["Compare.Title"] = "Repository Comparison",
        ["Compare.AddRepo"] = "Add Repository",
        ["Compare.Clear"] = "Clear All",
        ["Compare.Compare"] = "Compare",
        ["Compare.AddFirst"] = "Add repositories to compare",
        ["Compare.Max"] = "Maximum 4 repositories can be compared",

        // Reports
        ["Report.Title"] = "Reports",
        ["Report.Generate"] = "Generate Report",
        ["Report.Format"] = "Format",
        ["Report.PDF"] = "PDF",
        ["Report.Markdown"] = "Markdown",
        ["Report.HTML"] = "HTML",
        ["Report.OutputPath"] = "Output Path",
        ["Report.Browse"] = "Browse",
        ["Report.Generating"] = "Generating report...",
        ["Report.Success"] = "Report generated successfully!",
        ["Report.Open"] = "Open Report",
        ["Report.Repository"] = "Repository Report",
        ["Report.Organization"] = "Organization Report",
        ["Report.Security"] = "Security Report",
        ["Report.Comparison"] = "Comparison Report",

        // Settings
        ["Settings.Title"] = "Settings",
        ["Settings.Appearance"] = "Appearance",
        ["Settings.Language"] = "Language",
        ["Settings.GitHub"] = "GitHub",
        ["Settings.AI"] = "AI Configuration",
        ["Settings.Updates"] = "Updates",
        ["Settings.Privacy"] = "Privacy",
        ["Settings.Cache"] = "Cache",
        ["Settings.Security"] = "Security",
        ["Settings.About"] = "About",
        ["Settings.Theme"] = "Theme",
        ["Settings.ThemeSystem"] = "System",
        ["Settings.ThemeLight"] = "Light",
        ["Settings.ThemeDark"] = "Dark",
        ["Settings.LanguageEn"] = "English",
        ["Settings.LanguageTr"] = "Turkish",
        ["Settings.LanguageRu"] = "Russian",
        ["Settings.AiProvider"] = "AI Provider",
        ["Settings.OpenAiKey"] = "OpenAI API Key",
        ["Settings.OpenAiModel"] = "OpenAI Model",
        ["Settings.OllamaEndpoint"] = "Ollama Endpoint",
        ["Settings.OllamaModel"] = "Ollama Model",
        ["Settings.EnableNotifications"] = "Enable Notifications",
        ["Settings.EnableAnimations"] = "Enable Animations",
        ["Settings.EnableAutoUpdate"] = "Check for Updates Automatically",
        ["Settings.EnableTelemetry"] = "Send Anonymous Usage Data",
        ["Settings.CacheDuration"] = "Cache Duration (minutes)",
        ["Settings.EnableCaching"] = "Enable Caching",
        ["Settings.ReportsPath"] = "Default Reports Output Path",
        ["Settings.StartWithWindows"] = "Start with Windows",
        ["Settings.MinimizeToTray"] = "Minimize to Tray",
        ["Settings.Save"] = "Save Settings",
        ["Settings.Reset"] = "Reset to Defaults",
        ["Settings.Saved"] = "Settings saved successfully!",
        ["Settings.ClearCache"] = "Clear Cache",
        ["Settings.CacheCleared"] = "Cache cleared.",
        ["Settings.ExportLogs"] = "Export Logs",

        // Favorites
        ["Favorites.Title"] = "Favorites",
        ["Favorites.Empty"] = "No favorites yet. Analyze a repository and add it to favorites.",
        ["Favorites.Remove"] = "Remove",
        ["Favorites.Note"] = "Add Note",
        ["Favorites.EditNote"] = "Edit Note",

        // Logs
        ["Logs.Title"] = "Application Logs",
        ["Logs.Clear"] = "Clear Logs",
        ["Logs.Export"] = "Export Logs",
        ["Logs.Filter"] = "Filter by Level",
        ["Logs.All"] = "All",
        ["Logs.Info"] = "Information",
        ["Logs.Warning"] = "Warning",
        ["Logs.Error"] = "Error",
        ["Logs.Empty"] = "No logs to display.",

        // Notifications
        ["Notif.Success"] = "Success",
        ["Notif.Warning"] = "Warning",
        ["Notif.Error"] = "Error",
        ["Notif.Info"] = "Information",
        ["Notif.Close"] = "Close",

        // Common
        ["Common.Loading"] = "Loading...",
        ["Common.Error"] = "An error occurred.",
        ["Common.Retry"] = "Retry",
        ["Common.Cancel"] = "Cancel",
        ["Common.Close"] = "Close",
        ["Common.Save"] = "Save",
        ["Common.Delete"] = "Delete",
        ["Common.Edit"] = "Edit",
        ["Common.Add"] = "Add",
        ["Common.Remove"] = "Remove",
        ["Common.Search"] = "Search",
        ["Common.Filter"] = "Filter",
        ["Common.Sort"] = "Sort",
        ["Common.Export"] = "Export",
        ["Common.Import"] = "Import",
        ["Common.Copy"] = "Copy",
        ["Common.Open"] = "Open",
        ["Common.Back"] = "Back",
        ["Common.Next"] = "Next",
        ["Common.Yes"] = "Yes",
        ["Common.No"] = "No",
        ["Common.OK"] = "OK",
        ["Common.NotAvailable"] = "N/A",
        ["Common.Days"] = "days",
        ["Common.Ago"] = "ago",
        ["Common.Version"] = "Version",
        ["Common.By"] = "by",
    };

    private static Dictionary<string, string> GetTurkishStrings() => new()
    {
        ["Nav.Dashboard"] = "Gösterge Paneli",
        ["Nav.Repositories"] = "Depolar",
        ["Nav.Analyze"] = "Analiz Et",
        ["Nav.Trending"] = "Trend",
        ["Nav.Organizations"] = "Organizasyonlar",
        ["Nav.Contributors"] = "Katkıda Bulunanlar",
        ["Nav.Compare"] = "Karşılaştır",
        ["Nav.Security"] = "Güvenlik",
        ["Nav.AI"] = "AI Analizleri",
        ["Nav.Reports"] = "Raporlar",
        ["Nav.Favorites"] = "Favoriler",
        ["Nav.Logs"] = "Kayıtlar",
        ["Nav.Settings"] = "Ayarlar",

        ["Auth.SignIn"] = "GitHub ile Giriş Yap",
        ["Auth.SignOut"] = "Çıkış Yap",
        ["Auth.EnterToken"] = "GitHub Kişisel Erişim Tokeni Girin",
        ["Auth.TokenPlaceholder"] = "ghp_xxxxxxxxxxxxxxxxxxxx",
        ["Auth.SignInButton"] = "Kimlik Doğrula",
        ["Auth.Cancel"] = "İptal",
        ["Auth.Authenticating"] = "Kimlik doğrulanıyor...",
        ["Auth.Success"] = "Başarıyla giriş yapıldı!",
        ["Auth.Failed"] = "Kimlik doğrulama başarısız. Tokeninizi kontrol edin.",
        ["Auth.TokenHelp"] = "GitHub Ayarlar → Geliştirici ayarları → Kişisel erişim tokenları kısmından token oluşturun",
        ["Auth.Required"] = "GitHub kimlik doğrulaması gereklidir.",
        ["Auth.SwitchAccount"] = "Hesap Değiştir",
        ["Auth.ManageTokens"] = "Tokenleri Yönet",

        ["Dashboard.Title"] = "Gösterge Paneli",
        ["Dashboard.Welcome"] = "Tekrar hoş geldiniz,",
        ["Dashboard.TotalRepos"] = "Toplam Depolar",
        ["Dashboard.TotalStars"] = "Toplam Yıldızlar",
        ["Dashboard.TotalForks"] = "Toplam Çatallamalar",
        ["Dashboard.OpenIssues"] = "Açık Sorunlar",
        ["Dashboard.PullRequests"] = "Çekme İstekleri",
        ["Dashboard.Followers"] = "Takipçiler",
        ["Dashboard.Following"] = "Takip Edilenler",
        ["Dashboard.RecentActivity"] = "Son Aktivite",
        ["Dashboard.TopRepositories"] = "En İyi Depolar",
        ["Dashboard.Loading"] = "Gösterge paneli yükleniyor...",
        ["Dashboard.Refresh"] = "Yenile",
        ["Dashboard.ViewAll"] = "Tümünü Gör",
        ["Dashboard.Contributions"] = "Katkılar",
        ["Dashboard.PublicRepos"] = "Genel Depolar",

        ["Repo.Analyze"] = "Depoyu Analiz Et",
        ["Repo.SearchPlaceholder"] = "Sahip/depo adı veya URL girin...",
        ["Repo.Search"] = "Ara",
        ["Repo.Analyzing"] = "Depo analiz ediliyor...",
        ["Repo.NotFound"] = "Depo bulunamadı.",
        ["Repo.HealthScore"] = "Sağlık Puanı",
        ["Repo.MaintenanceScore"] = "Bakım Puanı",
        ["Repo.SecurityScore"] = "Güvenlik Puanı",
        ["Repo.CommunityScore"] = "Topluluk Puanı",
        ["Repo.PopularityScore"] = "Popülerlik Puanı",
        ["Repo.ActivityScore"] = "Aktivite Puanı",
        ["Repo.Stars"] = "Yıldızlar",
        ["Repo.Forks"] = "Çatallamalar",
        ["Repo.Watchers"] = "İzleyenler",
        ["Repo.Issues"] = "Sorunlar",
        ["Repo.Language"] = "Dil",
        ["Repo.License"] = "Lisans",
        ["Repo.Created"] = "Oluşturuldu",
        ["Repo.Updated"] = "Güncellendi",
        ["Repo.LastCommit"] = "Son Commit",
        ["Repo.Contributors"] = "Katkıda Bulunanlar",
        ["Repo.Releases"] = "Sürümler",
        ["Repo.Branches"] = "Dallar",
        ["Repo.Recommendations"] = "Öneriler",
        ["Repo.Warnings"] = "Uyarılar",
        ["Repo.Documentation"] = "Dokümantasyon",
        ["Repo.OpenGitHub"] = "GitHub'da Aç",
        ["Repo.AddFavorite"] = "Favorilere Ekle",
        ["Repo.RemoveFavorite"] = "Favorilerden Çıkar",
        ["Repo.GenerateReport"] = "Rapor Oluştur",
        ["Repo.AiAnalysis"] = "AI Analizi",
        ["Repo.Topics"] = "Konular",
        ["Repo.CloneUrl"] = "Klon URL'si",
        ["Repo.CopyUrl"] = "URL'yi Kopyala",
        ["Repo.Compare"] = "Karşılaştır",

        ["Score.Excellent"] = "Mükemmel",
        ["Score.Good"] = "İyi",
        ["Score.Fair"] = "Orta",
        ["Score.Poor"] = "Zayıf",
        ["Score.Critical"] = "Kritik",

        ["Trending.Title"] = "Trend Depolar",
        ["Trending.Today"] = "Bugün",
        ["Trending.ThisWeek"] = "Bu Hafta",
        ["Trending.ThisMonth"] = "Bu Ay",
        ["Trending.AllLanguages"] = "Tüm Diller",
        ["Trending.FilterLanguage"] = "Dile Göre Filtrele",
        ["Trending.Loading"] = "Trend depolar yükleniyor...",
        ["Trending.Developers"] = "Trend Geliştiriciler",

        ["Security.Title"] = "Güvenlik Merkezi",
        ["Security.Analyze"] = "Güvenlik Analizi",
        ["Security.Alerts"] = "Güvenlik Uyarıları",
        ["Security.NoAlerts"] = "Güvenlik sorunu bulunamadı.",
        ["Security.RiskLevel"] = "Risk Seviyesi",
        ["Security.Category"] = "Kategori",
        ["Security.Recommendation"] = "Öneri",
        ["Security.Critical"] = "Kritik",
        ["Security.High"] = "Yüksek",
        ["Security.Medium"] = "Orta",
        ["Security.Low"] = "Düşük",
        ["Security.None"] = "Yok",
        ["Security.Report"] = "Güvenlik Raporu",

        ["AI.Title"] = "AI Analizleri",
        ["AI.Summary"] = "Depo Özeti",
        ["AI.Adoption"] = "Benimseme Önerisi",
        ["AI.Risk"] = "Risk Raporu",
        ["AI.Improvements"] = "İyileştirme Önerileri",
        ["AI.Ask"] = "AI'ya Sor",
        ["AI.Placeholder"] = "Bu depo hakkında bir şeyler sorun...",
        ["AI.Generating"] = "AI analizi oluşturuluyor...",
        ["AI.Provider"] = "AI Sağlayıcı",
        ["AI.NotConfigured"] = "AI yapılandırılmamış. Ayarlar → AI bölümünden API anahtarınızı girin.",
        ["AI.Copy"] = "Yanıtı Kopyala",
        ["AI.Regenerate"] = "Yeniden Oluştur",

        ["Org.Title"] = "Organizasyonlar",
        ["Org.Search"] = "Organizasyon Ara",
        ["Org.Members"] = "Üyeler",
        ["Org.Teams"] = "Takımlar",
        ["Org.Repositories"] = "Depolar",
        ["Org.NotFound"] = "Organizasyon bulunamadı.",
        ["Org.Loading"] = "Organizasyon yükleniyor...",

        ["Contrib.Title"] = "Katkıda Bulunanlar",
        ["Contrib.Search"] = "Katkıda Bulunan Ara",
        ["Contrib.Commits"] = "Commitler",
        ["Contrib.Activity"] = "Aktivite",
        ["Contrib.Timeline"] = "Katkı Zaman Çizelgesi",
        ["Contrib.TopContributors"] = "En İyi Katkıda Bulunanlar",
        ["Contrib.Loading"] = "Katkıda bulunanlar yükleniyor...",

        ["Compare.Title"] = "Depo Karşılaştırma",
        ["Compare.AddRepo"] = "Depo Ekle",
        ["Compare.Clear"] = "Tümünü Temizle",
        ["Compare.Compare"] = "Karşılaştır",
        ["Compare.AddFirst"] = "Karşılaştırmak için depo ekleyin",
        ["Compare.Max"] = "En fazla 4 depo karşılaştırılabilir",

        ["Report.Title"] = "Raporlar",
        ["Report.Generate"] = "Rapor Oluştur",
        ["Report.Format"] = "Format",
        ["Report.PDF"] = "PDF",
        ["Report.Markdown"] = "Markdown",
        ["Report.HTML"] = "HTML",
        ["Report.OutputPath"] = "Çıktı Yolu",
        ["Report.Browse"] = "Gözat",
        ["Report.Generating"] = "Rapor oluşturuluyor...",
        ["Report.Success"] = "Rapor başarıyla oluşturuldu!",
        ["Report.Open"] = "Raporu Aç",
        ["Report.Repository"] = "Depo Raporu",
        ["Report.Organization"] = "Organizasyon Raporu",
        ["Report.Security"] = "Güvenlik Raporu",
        ["Report.Comparison"] = "Karşılaştırma Raporu",

        ["Settings.Title"] = "Ayarlar",
        ["Settings.Appearance"] = "Görünüm",
        ["Settings.Language"] = "Dil",
        ["Settings.GitHub"] = "GitHub",
        ["Settings.AI"] = "AI Yapılandırması",
        ["Settings.Updates"] = "Güncellemeler",
        ["Settings.Privacy"] = "Gizlilik",
        ["Settings.Cache"] = "Önbellek",
        ["Settings.Security"] = "Güvenlik",
        ["Settings.About"] = "Hakkında",
        ["Settings.Theme"] = "Tema",
        ["Settings.ThemeSystem"] = "Sistem",
        ["Settings.ThemeLight"] = "Açık",
        ["Settings.ThemeDark"] = "Koyu",
        ["Settings.LanguageEn"] = "İngilizce",
        ["Settings.LanguageTr"] = "Türkçe",
        ["Settings.LanguageRu"] = "Rusça",
        ["Settings.AiProvider"] = "AI Sağlayıcı",
        ["Settings.OpenAiKey"] = "OpenAI API Anahtarı",
        ["Settings.OpenAiModel"] = "OpenAI Modeli",
        ["Settings.OllamaEndpoint"] = "Ollama Endpoint",
        ["Settings.OllamaModel"] = "Ollama Modeli",
        ["Settings.EnableNotifications"] = "Bildirimleri Etkinleştir",
        ["Settings.EnableAnimations"] = "Animasyonları Etkinleştir",
        ["Settings.EnableAutoUpdate"] = "Güncellemeleri Otomatik Kontrol Et",
        ["Settings.EnableTelemetry"] = "Anonim Kullanım Verisi Gönder",
        ["Settings.CacheDuration"] = "Önbellek Süresi (dakika)",
        ["Settings.EnableCaching"] = "Önbelleği Etkinleştir",
        ["Settings.ReportsPath"] = "Varsayılan Rapor Çıktı Yolu",
        ["Settings.StartWithWindows"] = "Windows ile Başlat",
        ["Settings.MinimizeToTray"] = "Sistem Tepsisine Küçült",
        ["Settings.Save"] = "Ayarları Kaydet",
        ["Settings.Reset"] = "Varsayılana Sıfırla",
        ["Settings.Saved"] = "Ayarlar başarıyla kaydedildi!",
        ["Settings.ClearCache"] = "Önbelleği Temizle",
        ["Settings.CacheCleared"] = "Önbellek temizlendi.",
        ["Settings.ExportLogs"] = "Kayıtları Dışa Aktar",

        ["Favorites.Title"] = "Favoriler",
        ["Favorites.Empty"] = "Henüz favori yok. Bir depoyu analiz edin ve favorilere ekleyin.",
        ["Favorites.Remove"] = "Kaldır",
        ["Favorites.Note"] = "Not Ekle",
        ["Favorites.EditNote"] = "Notu Düzenle",

        ["Logs.Title"] = "Uygulama Kayıtları",
        ["Logs.Clear"] = "Kayıtları Temizle",
        ["Logs.Export"] = "Kayıtları Dışa Aktar",
        ["Logs.Filter"] = "Seviyeye Göre Filtrele",
        ["Logs.All"] = "Tümü",
        ["Logs.Info"] = "Bilgi",
        ["Logs.Warning"] = "Uyarı",
        ["Logs.Error"] = "Hata",
        ["Logs.Empty"] = "Görüntülenecek kayıt yok.",

        ["Notif.Success"] = "Başarılı",
        ["Notif.Warning"] = "Uyarı",
        ["Notif.Error"] = "Hata",
        ["Notif.Info"] = "Bilgi",
        ["Notif.Close"] = "Kapat",

        ["Common.Loading"] = "Yükleniyor...",
        ["Common.Error"] = "Bir hata oluştu.",
        ["Common.Retry"] = "Yeniden Dene",
        ["Common.Cancel"] = "İptal",
        ["Common.Close"] = "Kapat",
        ["Common.Save"] = "Kaydet",
        ["Common.Delete"] = "Sil",
        ["Common.Edit"] = "Düzenle",
        ["Common.Add"] = "Ekle",
        ["Common.Remove"] = "Kaldır",
        ["Common.Search"] = "Ara",
        ["Common.Filter"] = "Filtrele",
        ["Common.Sort"] = "Sırala",
        ["Common.Export"] = "Dışa Aktar",
        ["Common.Import"] = "İçe Aktar",
        ["Common.Copy"] = "Kopyala",
        ["Common.Open"] = "Aç",
        ["Common.Back"] = "Geri",
        ["Common.Next"] = "İleri",
        ["Common.Yes"] = "Evet",
        ["Common.No"] = "Hayır",
        ["Common.OK"] = "Tamam",
        ["Common.NotAvailable"] = "Yok",
        ["Common.Days"] = "gün",
        ["Common.Ago"] = "önce",
        ["Common.Version"] = "Sürüm",
        ["Common.By"] = "tarafından",
    };

    private static Dictionary<string, string> GetRussianStrings() => new()
    {
        ["Nav.Dashboard"] = "Панель управления",
        ["Nav.Repositories"] = "Репозитории",
        ["Nav.Analyze"] = "Анализ",
        ["Nav.Trending"] = "Тренды",
        ["Nav.Organizations"] = "Организации",
        ["Nav.Contributors"] = "Участники",
        ["Nav.Compare"] = "Сравнение",
        ["Nav.Security"] = "Безопасность",
        ["Nav.AI"] = "AI-анализ",
        ["Nav.Reports"] = "Отчёты",
        ["Nav.Favorites"] = "Избранное",
        ["Nav.Logs"] = "Журналы",
        ["Nav.Settings"] = "Настройки",

        ["Auth.SignIn"] = "Войти через GitHub",
        ["Auth.SignOut"] = "Выйти",
        ["Auth.EnterToken"] = "Введите персональный токен GitHub",
        ["Auth.TokenPlaceholder"] = "ghp_xxxxxxxxxxxxxxxxxxxx",
        ["Auth.SignInButton"] = "Аутентификация",
        ["Auth.Cancel"] = "Отмена",
        ["Auth.Authenticating"] = "Аутентификация...",
        ["Auth.Success"] = "Успешная аутентификация!",
        ["Auth.Failed"] = "Ошибка аутентификации. Проверьте токен.",
        ["Auth.TokenHelp"] = "Создайте токен в GitHub Settings → Developer settings → Personal access tokens",
        ["Auth.Required"] = "Требуется аутентификация GitHub.",
        ["Auth.SwitchAccount"] = "Сменить аккаунт",
        ["Auth.ManageTokens"] = "Управление токенами",

        ["Dashboard.Title"] = "Панель управления",
        ["Dashboard.Welcome"] = "С возвращением,",
        ["Dashboard.TotalRepos"] = "Всего репозиториев",
        ["Dashboard.TotalStars"] = "Всего звёзд",
        ["Dashboard.TotalForks"] = "Всего форков",
        ["Dashboard.OpenIssues"] = "Открытые задачи",
        ["Dashboard.PullRequests"] = "Pull Requests",
        ["Dashboard.Followers"] = "Подписчики",
        ["Dashboard.Following"] = "Подписки",
        ["Dashboard.RecentActivity"] = "Последняя активность",
        ["Dashboard.TopRepositories"] = "Лучшие репозитории",
        ["Dashboard.Loading"] = "Загрузка панели...",
        ["Dashboard.Refresh"] = "Обновить",
        ["Dashboard.ViewAll"] = "Показать все",
        ["Dashboard.Contributions"] = "Вклады",
        ["Dashboard.PublicRepos"] = "Публичные репозитории",

        ["Repo.Analyze"] = "Анализировать репозиторий",
        ["Repo.SearchPlaceholder"] = "Введите владелец/репозиторий или URL...",
        ["Repo.Search"] = "Поиск",
        ["Repo.Analyzing"] = "Анализ репозитория...",
        ["Repo.NotFound"] = "Репозиторий не найден.",
        ["Repo.HealthScore"] = "Оценка здоровья",
        ["Repo.MaintenanceScore"] = "Оценка обслуживания",
        ["Repo.SecurityScore"] = "Оценка безопасности",
        ["Repo.CommunityScore"] = "Оценка сообщества",
        ["Repo.PopularityScore"] = "Оценка популярности",
        ["Repo.ActivityScore"] = "Оценка активности",
        ["Repo.Stars"] = "Звёзды",
        ["Repo.Forks"] = "Форки",
        ["Repo.Watchers"] = "Наблюдатели",
        ["Repo.Issues"] = "Задачи",
        ["Repo.Language"] = "Язык",
        ["Repo.License"] = "Лицензия",
        ["Repo.Created"] = "Создан",
        ["Repo.Updated"] = "Обновлён",
        ["Repo.LastCommit"] = "Последний коммит",
        ["Repo.Contributors"] = "Участники",
        ["Repo.Releases"] = "Релизы",
        ["Repo.Branches"] = "Ветки",
        ["Repo.Recommendations"] = "Рекомендации",
        ["Repo.Warnings"] = "Предупреждения",
        ["Repo.Documentation"] = "Документация",
        ["Repo.OpenGitHub"] = "Открыть на GitHub",
        ["Repo.AddFavorite"] = "Добавить в избранное",
        ["Repo.RemoveFavorite"] = "Убрать из избранного",
        ["Repo.GenerateReport"] = "Создать отчёт",
        ["Repo.AiAnalysis"] = "AI-анализ",
        ["Repo.Topics"] = "Темы",
        ["Repo.CloneUrl"] = "URL клонирования",
        ["Repo.CopyUrl"] = "Скопировать URL",
        ["Repo.Compare"] = "Сравнить",

        ["Score.Excellent"] = "Отлично",
        ["Score.Good"] = "Хорошо",
        ["Score.Fair"] = "Удовлетворительно",
        ["Score.Poor"] = "Плохо",
        ["Score.Critical"] = "Критично",

        ["Trending.Title"] = "Трендовые репозитории",
        ["Trending.Today"] = "Сегодня",
        ["Trending.ThisWeek"] = "Эта неделя",
        ["Trending.ThisMonth"] = "Этот месяц",
        ["Trending.AllLanguages"] = "Все языки",
        ["Trending.FilterLanguage"] = "Фильтр по языку",
        ["Trending.Loading"] = "Загрузка трендов...",
        ["Trending.Developers"] = "Трендовые разработчики",

        ["Security.Title"] = "Центр безопасности",
        ["Security.Analyze"] = "Анализ безопасности",
        ["Security.Alerts"] = "Предупреждения безопасности",
        ["Security.NoAlerts"] = "Проблем безопасности не найдено.",
        ["Security.RiskLevel"] = "Уровень риска",
        ["Security.Category"] = "Категория",
        ["Security.Recommendation"] = "Рекомендация",
        ["Security.Critical"] = "Критический",
        ["Security.High"] = "Высокий",
        ["Security.Medium"] = "Средний",
        ["Security.Low"] = "Низкий",
        ["Security.None"] = "Нет",
        ["Security.Report"] = "Отчёт безопасности",

        ["AI.Title"] = "AI-анализ",
        ["AI.Summary"] = "Краткое описание",
        ["AI.Adoption"] = "Рекомендация по внедрению",
        ["AI.Risk"] = "Отчёт о рисках",
        ["AI.Improvements"] = "Предложения по улучшению",
        ["AI.Ask"] = "Спросить AI",
        ["AI.Placeholder"] = "Задайте вопрос об этом репозитории...",
        ["AI.Generating"] = "Генерация AI-анализа...",
        ["AI.Provider"] = "AI-провайдер",
        ["AI.NotConfigured"] = "AI не настроен. Укажите ключ API в Настройках → AI.",
        ["AI.Copy"] = "Скопировать ответ",
        ["AI.Regenerate"] = "Перегенерировать",

        ["Org.Title"] = "Организации",
        ["Org.Search"] = "Поиск организации",
        ["Org.Members"] = "Участники",
        ["Org.Teams"] = "Команды",
        ["Org.Repositories"] = "Репозитории",
        ["Org.NotFound"] = "Организация не найдена.",
        ["Org.Loading"] = "Загрузка организации...",

        ["Contrib.Title"] = "Участники",
        ["Contrib.Search"] = "Поиск участников",
        ["Contrib.Commits"] = "Коммиты",
        ["Contrib.Activity"] = "Активность",
        ["Contrib.Timeline"] = "Хронология вкладов",
        ["Contrib.TopContributors"] = "Лучшие участники",
        ["Contrib.Loading"] = "Загрузка участников...",

        ["Compare.Title"] = "Сравнение репозиториев",
        ["Compare.AddRepo"] = "Добавить репозиторий",
        ["Compare.Clear"] = "Очистить всё",
        ["Compare.Compare"] = "Сравнить",
        ["Compare.AddFirst"] = "Добавьте репозитории для сравнения",
        ["Compare.Max"] = "Можно сравнивать не более 4 репозиториев",

        ["Report.Title"] = "Отчёты",
        ["Report.Generate"] = "Создать отчёт",
        ["Report.Format"] = "Формат",
        ["Report.PDF"] = "PDF",
        ["Report.Markdown"] = "Markdown",
        ["Report.HTML"] = "HTML",
        ["Report.OutputPath"] = "Путь сохранения",
        ["Report.Browse"] = "Обзор",
        ["Report.Generating"] = "Создание отчёта...",
        ["Report.Success"] = "Отчёт успешно создан!",
        ["Report.Open"] = "Открыть отчёт",
        ["Report.Repository"] = "Отчёт по репозиторию",
        ["Report.Organization"] = "Отчёт по организации",
        ["Report.Security"] = "Отчёт безопасности",
        ["Report.Comparison"] = "Сравнительный отчёт",

        ["Settings.Title"] = "Настройки",
        ["Settings.Appearance"] = "Внешний вид",
        ["Settings.Language"] = "Язык",
        ["Settings.GitHub"] = "GitHub",
        ["Settings.AI"] = "Настройка AI",
        ["Settings.Updates"] = "Обновления",
        ["Settings.Privacy"] = "Конфиденциальность",
        ["Settings.Cache"] = "Кэш",
        ["Settings.Security"] = "Безопасность",
        ["Settings.About"] = "О программе",
        ["Settings.Theme"] = "Тема",
        ["Settings.ThemeSystem"] = "Системная",
        ["Settings.ThemeLight"] = "Светлая",
        ["Settings.ThemeDark"] = "Тёмная",
        ["Settings.LanguageEn"] = "Английский",
        ["Settings.LanguageTr"] = "Турецкий",
        ["Settings.LanguageRu"] = "Русский",
        ["Settings.AiProvider"] = "AI-провайдер",
        ["Settings.OpenAiKey"] = "Ключ API OpenAI",
        ["Settings.OpenAiModel"] = "Модель OpenAI",
        ["Settings.OllamaEndpoint"] = "Адрес Ollama",
        ["Settings.OllamaModel"] = "Модель Ollama",
        ["Settings.EnableNotifications"] = "Включить уведомления",
        ["Settings.EnableAnimations"] = "Включить анимации",
        ["Settings.EnableAutoUpdate"] = "Автопроверка обновлений",
        ["Settings.EnableTelemetry"] = "Отправлять анонимные данные",
        ["Settings.CacheDuration"] = "Время кэша (минуты)",
        ["Settings.EnableCaching"] = "Включить кэширование",
        ["Settings.ReportsPath"] = "Путь сохранения отчётов",
        ["Settings.StartWithWindows"] = "Запускать с Windows",
        ["Settings.MinimizeToTray"] = "Сворачивать в трей",
        ["Settings.Save"] = "Сохранить настройки",
        ["Settings.Reset"] = "Сбросить к умолчаниям",
        ["Settings.Saved"] = "Настройки успешно сохранены!",
        ["Settings.ClearCache"] = "Очистить кэш",
        ["Settings.CacheCleared"] = "Кэш очищен.",
        ["Settings.ExportLogs"] = "Экспорт журналов",

        ["Favorites.Title"] = "Избранное",
        ["Favorites.Empty"] = "Избранное пусто. Проанализируйте репозиторий и добавьте его.",
        ["Favorites.Remove"] = "Удалить",
        ["Favorites.Note"] = "Добавить заметку",
        ["Favorites.EditNote"] = "Редактировать заметку",

        ["Logs.Title"] = "Журнал событий",
        ["Logs.Clear"] = "Очистить журнал",
        ["Logs.Export"] = "Экспорт журнала",
        ["Logs.Filter"] = "Фильтр по уровню",
        ["Logs.All"] = "Все",
        ["Logs.Info"] = "Информация",
        ["Logs.Warning"] = "Предупреждение",
        ["Logs.Error"] = "Ошибка",
        ["Logs.Empty"] = "Журнал пуст.",

        ["Notif.Success"] = "Успех",
        ["Notif.Warning"] = "Предупреждение",
        ["Notif.Error"] = "Ошибка",
        ["Notif.Info"] = "Информация",
        ["Notif.Close"] = "Закрыть",

        ["Common.Loading"] = "Загрузка...",
        ["Common.Error"] = "Произошла ошибка.",
        ["Common.Retry"] = "Повторить",
        ["Common.Cancel"] = "Отмена",
        ["Common.Close"] = "Закрыть",
        ["Common.Save"] = "Сохранить",
        ["Common.Delete"] = "Удалить",
        ["Common.Edit"] = "Изменить",
        ["Common.Add"] = "Добавить",
        ["Common.Remove"] = "Убрать",
        ["Common.Search"] = "Поиск",
        ["Common.Filter"] = "Фильтр",
        ["Common.Sort"] = "Сортировка",
        ["Common.Export"] = "Экспорт",
        ["Common.Import"] = "Импорт",
        ["Common.Copy"] = "Копировать",
        ["Common.Open"] = "Открыть",
        ["Common.Back"] = "Назад",
        ["Common.Next"] = "Далее",
        ["Common.Yes"] = "Да",
        ["Common.No"] = "Нет",
        ["Common.OK"] = "ОК",
        ["Common.NotAvailable"] = "Н/Д",
        ["Common.Days"] = "дн.",
        ["Common.Ago"] = "назад",
        ["Common.Version"] = "Версия",
        ["Common.By"] = "от",
    };
}
